### ISSUE TITLE
Красивий спосіб доступу до module.exports додатку з фреймворку

### ISSUE THREAD

**Issue by anxolerd** [HowProgrammingWorks/InversionOfControl#1]
Завдання №7:

> Export a hash from application.js with multiple functions and variables, print the list with types from framework

Теоретично можна використати `require` для виконання цієї задачі, але в цьому випадку затягувати прикладний код доведеться **двічі**: один раз для створення скрипта, а другий -- для отримання `exports` цього модуля. Більш того, код в такому випадку буде, що називається: "code smells" :hankey: .

Як красиво можна отримати `module.exports` завантажуваного застосунку, який виконується у пісочниці?

**Comment by tshemsedinov** [comment]
Вот тут в комментах я делал подсказку: https://github.com/HowProgrammingWorks/InversionOfControl/blob/master/sandboxedModule/en/framework.js#L22-L25

Пример:

``` JavaScript
// Запускаем script в sandbox
script.runInNewContext(sandbox);
// Смотри, что экспортирует модуль
console.dir(sandbox.module.exports);
```

**Comment by anxolerd** [comment]
Дякую.
