### ISSUE TITLE
Помилка при запуску застосунку interfaceWrapper

### ISSUE THREAD

**Issue by anxolerd** [HowProgrammingWorks/InversionOfControl#5]
# Помилка при запуску застосунку
## Опис

При сробі запуску застосунку [interfaceWrapper](https://github.com/HowProgrammingWorks/InversionOfControl/tree/master/interfaceWrapper), як це вказано в [README.md](https://github.com/HowProgrammingWorks/InversionOfControl/blame/master/interfaceWrapper/ru/README.md#L13-L17): 

> Из командной строки пишем node application, а потом node framework, сравниваем вывод

виникає помилка, що `fs` не визначено
## Кроки відтвореня
1. Перейти у директорію із відповідним завданням. Для цього у корені проекту виконати:
   `cd interfaceWrapper/ru`
2. Виконати команду, вказану у README.md:
   `node application.js`
## Очікуваний результат:

Застосунок виконується успішно
## Дійсний результат:

Під час виконання застосунку виникає помилка, що змінна `fs` не визначена:

``` bash
% node application.js 
From application global context
Application going to read ./README.md
/home/oleksandr/workspace/InversionOfControl/interfaceWrapper/ru/application.js:15
fs.readFile(fileName, function(err, src) {
^

ReferenceError: fs is not defined
    at Object.<anonymous> (/home/oleksandr/workspace/InversionOfControl/interfaceWrapper/ru/application.js:15:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
```

**Comment by tshemsedinov** [comment]
Да, я из `application.js` перенес пример вызова fs в описание лабы, но из файла не уделил. По ходу лабы этот кусок кода предлагается взять из описания и вставить в `application.js`, а он уже там. Удалил, спасибо!
