### ISSUE TITLE
Неправильна поведінка wrapFunction() у застосунку interfaceWrapper

### ISSUE THREAD

**Issue by anxolerd** [HowProgrammingWorks/InversionOfControl#7]
# Неправильна поведінка wrapFunction() у застосунку interfaceWrapper
## Опис

У завданні наведено таку реалізацію функції `wrapFunction`:

> ``` JavaScript
> function wrapFunction(fnName, fn) {
>   return function wrapper() {
>     var args = [];
>     Array.prototype.push.apply(args, arguments);
>     console.log('Call: ' + fnName);
>     console.dir(args);
>     fn.apply(undefined, args);
>   }
> }
> ```

Дана реалзіація цієї функції ламає виконання програм, де використовується результат, який повертає оригінальна функція, оскільки обгортка не повертає результату (точніше, повертає `undefined`) і результат функції губиться.
## Пропозиція

Змінити реалізацію таким чином, щоб `wrapper` повертав результат оригінаьної функції.

``` JavaScript
return function wrapper() {
    ...
    return fn.apply(undefined, args);
}
```

**Comment by tshemsedinov** [comment]
Согласен, давай пулреквест

**Comment by anxolerd** [comment]
@tshemsedinov: PR у #10

**Comment by auliere** [comment]
А я-то подумал, что додуматься до этого изменения - это часть задания х)

**Comment by tshemsedinov** [comment]
Вот и чудно, @auliere, для нескольких человек это и стало частью задания )
